# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#
## PARENT MENU
#

[[main]]
name = "About Us"
pre = "circle-info"
pageRef = "about"
weight = 10

[[main]]
name = "Projects"
pre = "fork"
pageRef = "projects"
weight = 20

[[main]]
name = "Info/Writings"
pre = "edit"
pageRef = "info"
weight = 30

[[main]]
name = "Howto/Guides"
pre = "bars"
pageref = "guides"
weight = 40

#
## Projects

[[main]]
name = "Community Workshops & Trainings"
pre = "graduation-cap"
parent = "Projects"
pageRef = "projects/workshops"
weight = 10

[[main]]
name = "UpRiv|Upcycle: Community E-Waste Reclamation Program"
pre = "fork"
parent = "Projects"
pageRef = "projects/upcycle"
weight = 20

[[main]]
name = "Community-Owned Media"
pre = "youtube"
parent = "Projects"
pageRef = "projects/media"
weight = 30

[[main]]
name = "Youth Code Camp"
pre = "code"
parent = "Projects"
pageRef = "projects/code-camp"
weight = 40

[[main]]
name = "Solar-Powered, Mutual-Aid Comms Network"
pre = "rss"
parent = "Projects"
pageRef = "projects/mesh"
weight = 50

[[main]]
name = "Secure Data Erasure"
pre = "bomb"
parent = "Projects"
pageRef = "projects/secure-shred"
weight = 60

#
## Howto/Guides

[[main]]
name = "Privacy 101"
pre = "ghost"
parent = "Howto/Guides"
pageRef = "guides/privacy101/1-intro/"
weight = 20

[[main]]
name = "Advanced Privacy"
pre = "pgpkey"
parent = "Howto/Guides"
pageRef = "guides/advanced"
weight = 30

#
## Info/Writings

[[main]]
name = "Hacker Culture"
pre = "edit"
parent = "Info/Writings"
pageRef = "info/hacker_manifesto"
weight = 20

[[main]]
name = "Points of Unity"
pre = "edit"
parent = "Info/Writings"
pageRef = "info/points_of_unity"
weight = 10

[[main]]
name = "What is Techno-Colonialism?"
pre = "edit"
parent = "Info/Writings"
pageRef = "info/technocolonialism"
weight = 20

[[main]]
name = "What is #Data Back?"
pre = "edit"
parent = "Info/Writings"
pageRef = "info/data_back"
weight = 30

[[main]]
name = "Neo-Luddism: Peasant Revolts Against Predatory Tech"
pre = "edit"
parent = "Info/Writings"
pageRef = "info/technofeudalism"
weight = 40

[[main]]
name = "What is a 'Feminist Server Stack'?"
pre = "edit"
parent = "Info/Writings"
pageRef = "info/femme_srv"
weight = 60


[[main]]
name = "Hacking: A Timeline"
pre = "edit"
parent = "Info/Writings"
pageRef = "info/timeline"
weight = 60

[[main]]
name = "Modern-day Oracles or Bullshit Machines: How to thrive in a ChatGPT world"
pre = "edit"
parent = "Info/Writings"
url = "https://thebullshitmachines.com/index.html"
weight = 60

#
## SUB-NAV

[[subnavigation]]
  #name = "ğŸ…‚ğŸ…„ğŸ„±ğŸ…‚ğŸ„²ğŸ…ğŸ„¸ğŸ„±ğŸ„´"
  name = "SUBSCRIBE"
  pre = "envelope"
  pageRef = "subscribe"
  #url = "https://list.klamathtech.diy/subscription/form"
  weight = 30

[[subnavigation]]
#  name = "ğŸ„³ğŸ„¾ğŸ„½ğŸ„°ğŸ…ƒğŸ„´"
#  name = "DONATE"
#  pre = "donation"
#  pageRef = "subscribe"
#  #url = "https://list.klamathtech.diy/subscription/form"
#  weight = 20

#[[main]]
#name = "Categories"
#pageRef = "categories"
#weight = 20

#[[main]]
#name = "Tags"
#pageRef = "tags"
#weight = 30


#-- Footer Menu --
#The footer menu is displayed at the bottom of the page, just before
#the copyright notice. Configure as per the main menu above.


[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20

[[footer]]
name = "Authors"
pageRef = "authors"
weight = 20
